//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public Exam()
        {
            this.QuestionMarks = new HashSet<QuestionMark>();
        }
    
        public int Id { get; set; }
        public string ExamType { get; set; }
        public string ExamCode { get; set; }
        public string Topic { get; set; }
        public double FullMark { get; set; }
        public System.DateTime ExamDuration { get; set; }
        public int CourseId { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<QuestionMark> QuestionMarks { get; set; }
    }
}
